FROM openjdk:11
COPY ./target/DockerNetworkSpringBootApplication-0.0.1-SNAPSHOT.jar DockerNetworkSpringBootApplication-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","DockerNetworkSpringBootApplication-0.0.1-SNAPSHOT.jar"]